export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_COMPLETE = 'GET_ACTIVITIES_COMPLETE';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';
export const CLEAR_ACTIVITIES_COMPLETE = 'CLEAR_ACTIVITIES_COMPLETE';
export const GET_ACTIVITY_START = 'GET_ACTIVITY_START';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_ERROR = 'GET_ACTIVITY_ERROR';
export const CLEAR_ACTIVITY_ERROR = 'CLEAR_ACTIVITY_ERROR';

export const SET_CURRENT_ACTIVITY = 'SET_CURRENT_ACTIVITY';
export const ACTIVATE_CURRENT_ACTIVITY = 'ACTIVATE_CURRENT_ACTIVITY';
